version: 2.0.0
last_updated: '2026-01-01'
source: Sigma Specification 2.0 Appendix
products:
- canonical: apache
  type: application
  aliases:
  - Apache
  - APACHE
  - apache-httpd
  - httpd
  description: Apache HTTP Server
  sigma_spec_url: null
- canonical: django
  type: application
  aliases:
  - Django
  - DJANGO
  description: Django web framework
  sigma_spec_url: null
- canonical: iis
  type: application
  aliases:
  - IIS
  - iis
  - Microsoft IIS
  - Internet Information Services
  description: Microsoft Internet Information Services
  sigma_spec_url: null
- canonical: modsecurity
  type: application
  aliases:
  - ModSecurity
  - MODSECURITY
  - mod-security
  description: ModSecurity web application firewall
  sigma_spec_url: null
- canonical: nginx
  type: application
  aliases:
  - Nginx
  - NGINX
  - nginx-server
  description: Nginx web server
  sigma_spec_url: null
- canonical: python
  type: application
  aliases:
  - Python
  - PYTHON
  - python-app
  description: Python programming language
  sigma_spec_url: null
- canonical: spring
  type: application
  aliases:
  - Spring
  - SPRING
  - spring-boot
  - SpringBoot
  description: Spring Framework
  sigma_spec_url: null
- canonical: sql
  type: application
  aliases:
  - SQL
  - sql
  - database
  - db
  description: SQL database systems
  sigma_spec_url: null
- canonical: aws
  type: cloud
  aliases: []
  description: AWS CloudTrail audit logs
  sigma_spec_url: null
- canonical: aws
  type: cloud
  aliases: []
  description: AWS GuardDuty threat detection
  sigma_spec_url: null
- canonical: aws
  type: cloud
  aliases: []
  description: AWS S3 access logs
  sigma_spec_url: null
- canonical: aws
  type: cloud
  aliases:
  - AWS
  - Amazon Web Services
  - amazon
  - aws-cloud
  description: Amazon Web Services cloud platform
  sigma_spec_url: null
- canonical: azure
  type: cloud
  aliases: []
  description: Azure AD Audit Logs
  sigma_spec_url: null
- canonical: azure
  type: cloud
  aliases:
  - Azure
  - AZURE
  - Microsoft Azure
  - MS Azure
  - azure-cloud
  description: Microsoft Azure cloud platform
  sigma_spec_url: null
- canonical: azure
  type: cloud
  aliases: []
  description: Azure Activity Logs
  sigma_spec_url: null
- canonical: azure
  type: cloud
  aliases: []
  description: Azure AD Sign-in Logs
  sigma_spec_url: null
- canonical: gcp
  type: cloud
  aliases:
  - GCP
  - Google Cloud
  - google cloud platform
  - GoogleCloud
  - google
  description: Google Cloud Platform
  sigma_spec_url: null
- canonical: github
  type: cloud
  aliases:
  - GitHub
  - GITHUB
  - Github
  description: GitHub version control and collaboration platform
  sigma_spec_url: null
- canonical: m365
  type: cloud
  aliases:
  - M365
  - Microsoft 365
  - Office 365
  - O365
  - office365
  - microsoft365
  description: Microsoft 365 (Office 365) cloud services
  sigma_spec_url: null
- canonical: okta
  type: cloud
  aliases:
  - Okta
  - OKTA
  - okta-iam
  description: Okta identity and access management
  sigma_spec_url: null
- canonical: onelogin
  type: cloud
  aliases:
  - OneLogin
  - one-login
  - ONELOGIN
  description: OneLogin identity and access management
  sigma_spec_url: null
- canonical: salesforce
  type: cloud
  aliases:
  - Salesforce
  - SALESFORCE
  - SalesForce
  description: Salesforce CRM platform
  sigma_spec_url: null
- canonical: checkpoint
  type: network
  aliases:
  - Check Point
  - CheckPoint
  - CHECKPOINT
  - check-point
  - cp
  description: Check Point network security appliances
  sigma_spec_url: null
- canonical: cisco
  type: network
  aliases:
  - Cisco
  - CISCO
  - cisco-asa
  - Cisco ASA
  - cisco-firepower
  description: Cisco network devices (routers, switches, firewalls)
  sigma_spec_url: null
- canonical: fortinet
  type: network
  aliases:
  - Fortinet
  - FORTINET
  - FortiGate
  - fortigate
  - Forti
  description: Fortinet network security appliances
  sigma_spec_url: null
- canonical: huawei
  type: network
  aliases:
  - Huawei
  - HUAWEI
  description: Huawei network devices
  sigma_spec_url: null
- canonical: juniper
  type: network
  aliases:
  - Juniper
  - JUNIPER
  - juniper-srx
  - Juniper SRX
  description: Juniper Networks network devices
  sigma_spec_url: null
- canonical: paloalto
  type: network
  aliases:
  - Palo Alto
  - PaloAlto
  - PA
  - PAN-OS
  - palo-alto
  - Palo Alto Networks
  description: Palo Alto Networks firewalls
  sigma_spec_url: null
- canonical: zeek
  type: network
  aliases:
  - Zeek
  - ZEEK
  - Bro
  - BRO
  description: Zeek (Bro) network security monitor
  sigma_spec_url: null
- canonical: linux
  type: os
  aliases:
  - Linux
  - LINUX
  - Unix
  - UNIX
  - unix
  - GNU/Linux
  description: Linux operating system
  sigma_spec_url: null
- canonical: macos
  type: os
  aliases:
  - macOS
  - MacOS
  - MACOS
  - Mac OS
  - Darwin
  - darwin
  - OSX
  - osx
  description: Apple macOS operating system
  sigma_spec_url: null
- canonical: windows
  type: os
  aliases: []
  description: Windows Defender logs
  sigma_spec_url: null
- canonical: windows
  type: os
  aliases: []
  description: Windows Firewall (Advanced Security)
  sigma_spec_url: null
- canonical: windows
  type: os
  aliases: []
  description: Windows Task Scheduler
  sigma_spec_url: null
- canonical: windows
  type: os
  aliases: []
  description: Windows Sysmon (System Monitor) logs
  sigma_spec_url: null
- canonical: windows
  type: os
  aliases: []
  description: Windows Security Event Log
  sigma_spec_url: null
- canonical: windows
  type: os
  aliases:
  - Windows
  - WINDOWS
  - Microsoft Windows
  - Win
  - win
  - MS Windows
  description: Microsoft Windows operating system
  sigma_spec_url: null
- canonical: windows
  type: os
  aliases: []
  description: Windows WMI Activity logs
  sigma_spec_url: null
- canonical: windows
  type: os
  aliases: []
  description: Windows System Event Log
  sigma_spec_url: null
- canonical: windows
  type: os
  aliases: []
  description: Windows Application Event Log
  sigma_spec_url: null
- canonical: windows
  type: os
  aliases: []
  description: Windows PowerShell logs
  sigma_spec_url: null
