title: Device EDR settings are not compliant
id: 7bacde51-1a6d-4fdc-bd68-d65cd546bd01
status: experimental
level: medium
description: |
  KQL detection rule: Device EDR settings are not compliant
author: Bert-JanP
logsource:
  product: microsoft_security
  service: kql
detection:
  _kql_query: |
    DeviceTvmSecureConfigurationAssessment
| join kind=inner DeviceTvmSecureConfigurationAssessmentKB on ConfigurationId
| where IsCompliant == 0 and IsApplicable == 1
| where ConfigurationSubcategory == "EDR"
  condition: _kql_query
references:
  - https://github.com/Bert-JanP/Hunting-Queries-Detection-Rules
