title: Prioritize Secure Configuration
id: c717d085-74da-4f00-b1fb-de421a9ce71d
status: experimental
level: medium
description: |
  This query helps you prioritize configuration changes that affect your devices based on the Microsoft Defender TVM modules.
author: Bert-JanP
logsource:
  product: microsoft_security
  service: kql
detection:
  _kql_query: |
    DeviceTvmSecureConfigurationAssessment
| summarize TotalDevices = dcount(DeviceId) by ConfigurationId, ConfigurationCategory
| join kind=inner DeviceTvmSecureConfigurationAssessmentKB on ConfigurationId
| sort by ConfigurationImpact, TotalDevices
| project-reorder ConfigurationId, ConfigurationImpact, TotalDevices, ConfigurationName,  ConfigurationCategory, ConfigurationSubcategory
  condition: _kql_query
references:
  - https://github.com/Bert-JanP/Hunting-Queries-Detection-Rules
