signatures:
- vendor: mongodb
  product: database
  log_type: log
  version: null
  log_format: json
  signature_name: MongoDB Database Log
  primary_pattern: mongodb\.log|mongod|mongos
  confidence: 0.95
  priority: 5
  source: filebeat_import
  upstream_sources:
  - filebeat
