version: '1.0'
vendor: MongoDB
product: Database
product_full_name: Database
log_type: structured
source_document: ''
source_url: ''
extraction_date: '2026-02-12'
source_file: mongodb-database-signatures.json
generated_at: '2026-02-12T18:54:31.429247'
field_count: 0
fields: []
mapped_field_count: 0
signatures:
- name: mongodb_log
  description: MongoDB database log entry
  pattern: mongodb\.log|mongod|mongos
  event_type: database
  confidence: 0.95
