signatures:
- vendor: postgresql
  product: database
  log_type: error
  version: null
  log_format: syslog
  signature_name: PostgreSQL Error Log
  primary_pattern: 'ERROR:|FATAL:|PANIC:'
  confidence: 0.9
  priority: 5
  source: filebeat_import
  upstream_sources:
  - filebeat
- vendor: postgresql
  product: database
  log_type: log
  version: null
  log_format: syslog
  signature_name: PostgreSQL Database Log
  primary_pattern: 'postgresql\.log|LOG:|ERROR:|WARNING:'
  confidence: 0.95
  priority: 5
  source: filebeat_import
  upstream_sources:
  - filebeat
- vendor: postgresql
  product: database
  log_type: query
  version: null
  log_format: syslog
  signature_name: PostgreSQL Query Log
  primary_pattern: 'statement:|execute|duration:'
  confidence: 0.85
  priority: 10
  source: filebeat_import
  upstream_sources:
  - filebeat
