version: '1.0'
vendor: PostgreSQL
product: Database
product_full_name: Database
log_type: structured
source_document: ''
source_url: ''
extraction_date: '2026-01-29'
source_file: postgresql-database-signatures.json
generated_at: '2026-01-29T05:59:01.077726'
field_count: 0
fields: []
signatures:
- name: postgresql_log
  description: PostgreSQL database log entry
  pattern: 'postgresql\.log|LOG:|ERROR:|WARNING:|FATAL:'
  event_type: database
  confidence: 0.95
- name: postgresql_error
  description: PostgreSQL database error
  pattern: 'ERROR:|FATAL:|PANIC:'
  event_type: error
  confidence: 0.9
- name: postgresql_query
  description: PostgreSQL query execution
  pattern: statement:|execute|SELECT|INSERT|UPDATE|DELETE
  event_type: query
  confidence: 0.85
